### ISSUE TITLE
ChatCommand?

### ISSUE THREAD

**Issue by BiLachner** [zeuner/edutest#1]
Hallo,
wollte es gerade mal ausprobieren, aber es wird eine Abhängigkeit nicht erfüllt, nämlich "edutest_chatcommands"
Fehlt das noch oder wo bekommt man es dann her?

**Comment by zeuner** [comment]
Danke fuer den Hinweis, ich habe die README entsprechend ergaenzt.

Das ist als eigenstaendiges Paket (https://github.com/zeuner/edutest-chatcommands) online, da man es ggf. auch ohne die GUI benutzen wollen koennte.

**Comment by zeuner** [comment]
HTH

original message follows:
