### ISSUE TITLE
[Mod] Unsichtbarkeit?

### ISSUE THREAD

**Issue by BiLachner** [zeuner/edutest#11]
Habe da einen Mod gesehen, mit dem man sich unsichtbar machen kann. Oder gab es da schon einen anderen? Ich glaube darüber wurde schon gesprochen, oder?

https://forum.minetest.net/viewtopic.php?f=9&t=19050

**Comment by zeuner** [comment]
[English version below]

@Birgit Lachner: Ja, so etwas wurde schon einmal diskutiert, und wurde
auch eingebaut: https://github.com/zeuner/edutest/issues/6

Sieht aber aus, als sei es diesmal ein anderes Forenthema (und
Mod?). Bringt das Verbesserungen ueber die bereits verwendete
Implementierung hinaus?

-----

@Birgit Lachner: Yes, we had something like this before, which is
already integrated: https://github.com/zeuner/edutest/issues/6

Looks like this is a different forum thread (and mod?) now. Any
advantages over the existing implementation.

Originalnachricht:

**Comment by zeuner** [comment]
Ok.

original message follows:
