### ISSUE TITLE
Logo für den EDU-Knopf

### ISSUE THREAD

**Issue by BiLachner** [zeuner/edutest#5]
https://scontent.ftxl1-1.fna.fbcdn.net/v/t1.0-9/21034584_1868174419873363_396350493758408165_n.jpg?oh=d1c1d620a3814948365b8d5a5c52871f&oe=5A1B48EF

Hab wohl leider die SVG-Datei nicht gespeichert, aber notfalls noch einmal neu, um beliebige Auflösung zu bekommen.

**Comment by zeuner** [comment]
Sieht gut aus. Aber unter was fuer einer Lizenz steht das Logo?

Originalnachricht:

**Comment by BiLachner** [comment]
Ich stelle es als CC-0 zur Verfügung. Habe wohl dooferweise die svg-Datei gelöscht, aber das ist schnell neu gemacht.
EIgentlich reichen ja weiße Linien auf dem grauen Hintergrund. Deshalb ist das schwarze Quadrat dahitner wegzudenken. oder durch etwas unaufälligeres zu ersetzen, wie einen Rahmen oder Schatten.

**Comment by zeuner** [comment]
Ok, gut. Ich habe es jetzt mal vorlaeufig anhand der JPEG-Datei in den
"testing"-Branch (https://github.com/zeuner/edutest/tree/testing)
aufgenommen.

Originalnachricht:

**Comment by zeuner** [comment]
The logo integration from the testing branch has been merged into the master branch. So I regard this issue as solved.
