### ISSUE TITLE
Vorschlag: Sich unsichtbar machen können.

### ISSUE THREAD

**Issue by BiLachner** [zeuner/edutest#6]
Habe das gerade in einem Mod gefunden:
https://forum.minetest.net/viewtopic.php?f=9&t=17389

Nur ein Vorschlag, könnte aber interessant sein.

**Comment by zeuner** [comment]
Stimmt, die Unsichtbarkeits-Mod von octacian hat sich bei der Arbeit
mit Schuelergruppen bewaehrt, da man so auch z.B. etwas nachsehen oder
richten kann, ohne durch seine sichtbare Anwesenheit zur Interaktion
zu animieren.

Ich habe im "testing"-Branch einen Button dafuer eingebaut, damit es
(mit installierter "invis"-Mod) ohne Kommando tippen geht.

Originalnachricht:

**Comment by zeuner** [comment]
The invisibility mod support from the testing branch has been merged into the master branch. So I regard this issue as solved.

**Comment by zeuner** [comment]
[english version below]

@BiLachner: Wird unterstuetzt durch
https://github.com/zeuner/edutest/commit/41e475eba911db9be79f808fe3ac404545c575dd

--

@BiLachner: Is supported through
https://github.com/zeuner/edutest/commit/41e475eba911db9be79f808fe3ac404545c575dd

original message follows:
